"""Add orden to vehiculos

Revision ID: b7136e52843d
Revises: 008_pre_fase3
Create Date: 2026-05-22 14:46:32.033518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7136e52843d'
down_revision: Union[str, None] = '008_pre_fase3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alquileres', 'contrato_url',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('ix_alquileres_checkout_fecha', table_name='alquileres')
    op.drop_index('ix_clientes_dni_trgm', table_name='clientes', postgresql_using='gin')
    op.drop_index('ix_clientes_nombre_trgm', table_name='clientes', postgresql_using='gin')
    op.add_column('vehiculos', sa.Column('orden', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehiculos', 'orden')
    op.create_index('ix_clientes_nombre_trgm', 'clientes', ['nombre_completo'], unique=False, postgresql_using='gin')
    op.create_index('ix_clientes_dni_trgm', 'clientes', ['dni_cuit'], unique=False, postgresql_using='gin')
    op.create_index('ix_alquileres_checkout_fecha', 'alquileres', ['checkout_fecha'], unique=False)
    op.alter_column('alquileres', 'contrato_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###
