"""add_foto_key_to_vehiculo

Revision ID: c331c7365da8
Revises: e9cb23fe670f
Create Date: 2026-05-18 23:16:20.406782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c331c7365da8'
down_revision: Union[str, None] = 'e9cb23fe670f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehiculos', sa.Column('foto_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehiculos', 'foto_key')
    # ### end Alembic commands ###
