"""initial_schema

Revision ID: e9cb23fe670f
Revises: 
Create Date: 2026-05-18 22:54:43.452694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9cb23fe670f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('dni_cuit', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('licencia_numero', sa.String(length=50), nullable=False),
    sa.Column('licencia_vencimiento', sa.String(length=10), nullable=False),
    sa.Column('licencia_categoria', sa.String(length=5), nullable=False),
    sa.Column('tipo', sa.Enum('particular', 'empresa', name='tipo_cliente'), nullable=False),
    sa.Column('es_frecuente', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_dni_cuit'), 'clientes', ['dni_cuit'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_nombre_completo'), 'clientes', ['nombre_completo'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'docs', name='rol_usuario'), nullable=False),
    sa.Column('auth_sub', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_auth_sub'), 'usuarios', ['auth_sub'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patente', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('auto', 'camioneta', name='tipo_vehiculo'), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.Enum('disponible', 'alquilado', 'reservado', 'en_transicion', 'fuera_de_servicio', name='estado_vehiculo'), nullable=False),
    sa.Column('km_actual', sa.Integer(), nullable=False),
    sa.Column('km_proximo_service', sa.Integer(), nullable=False),
    sa.Column('km_entre_services', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculos_id'), 'vehiculos', ['id'], unique=False)
    op.create_index(op.f('ix_vehiculos_patente'), 'vehiculos', ['patente'], unique=True)
    op.create_table('conductores_adicionales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('licencia_numero', sa.String(length=50), nullable=False),
    sa.Column('licencia_vencimiento', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conductores_adicionales_cliente_id'), 'conductores_adicionales', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_conductores_adicionales_id'), 'conductores_adicionales', ['id'], unique=False)
    op.create_table('cuentas_corrientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuentas_corrientes_cliente_id'), 'cuentas_corrientes', ['cliente_id'], unique=True)
    op.create_index(op.f('ix_cuentas_corrientes_id'), 'cuentas_corrientes', ['id'], unique=False)
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('poliza', 'vtv', 'clausulas', 'otro', name='tipo_documento'), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('url_archivo', sa.String(length=512), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), nullable=False),
    sa.Column('vigencia_desde', sa.String(length=10), nullable=True),
    sa.Column('vigencia_hasta', sa.String(length=10), nullable=True),
    sa.Column('cargado_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cargado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_id'), 'documentos', ['id'], unique=False)
    op.create_index(op.f('ix_documentos_vehiculo_id'), 'documentos', ['vehiculo_id'], unique=False)
    op.create_index(op.f('ix_documentos_vigencia_hasta'), 'documentos', ['vigencia_hasta'], unique=False)
    op.create_table('gastos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('service', 'combustible', 'cubiertas', 'reparacion', 'seguro', 'patente', 'vtv', 'lavado', 'otro', name='tipo_gasto'), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('medio_pago', sa.Enum('efectivo', 'transferencia', 'tarjeta', 'cheque', 'echeq', name='medio_pago_gasto'), nullable=False),
    sa.Column('fecha', sa.String(length=10), nullable=False),
    sa.Column('proveedor', sa.String(length=255), nullable=True),
    sa.Column('km_al_momento', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gastos_fecha'), 'gastos', ['fecha'], unique=False)
    op.create_index(op.f('ix_gastos_id'), 'gastos', ['id'], unique=False)
    op.create_index(op.f('ix_gastos_vehiculo_id'), 'gastos', ['vehiculo_id'], unique=False)
    op.create_table('presupuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.String(length=10), nullable=False),
    sa.Column('fecha_fin', sa.String(length=10), nullable=False),
    sa.Column('dias', sa.Integer(), nullable=False),
    sa.Column('tarifa_unitaria', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('borrador', 'enviado', 'aceptado', 'vencido', name='estado_presupuesto'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presupuestos_id'), 'presupuestos', ['id'], unique=False)
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.String(length=10), nullable=False),
    sa.Column('hora_inicio', sa.String(length=5), nullable=False),
    sa.Column('fecha_fin', sa.String(length=10), nullable=False),
    sa.Column('hora_fin', sa.String(length=5), nullable=False),
    sa.Column('lugar_entrega', sa.String(length=255), nullable=False),
    sa.Column('lugar_devolucion', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'confirmada', 'activa', 'finalizada', 'cancelada', name='estado_reserva'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_cliente_id'), 'reservas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_reservas_id'), 'reservas', ['id'], unique=False)
    op.create_index(op.f('ix_reservas_vehiculo_id'), 'reservas', ['vehiculo_id'], unique=False)
    op.create_table('tarifas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('diaria', 'semanal', 'mensual', name='tipo_tarifa'), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarifas_id'), 'tarifas', ['id'], unique=False)
    op.create_index(op.f('ix_tarifas_vehiculo_id'), 'tarifas', ['vehiculo_id'], unique=False)
    op.create_table('alquileres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('checkout_fecha', sa.String(length=10), nullable=False),
    sa.Column('checkout_hora', sa.String(length=5), nullable=False),
    sa.Column('checkout_km', sa.Integer(), nullable=False),
    sa.Column('checkout_combustible', sa.Integer(), nullable=False),
    sa.Column('checkout_descripcion', sa.Text(), nullable=True),
    sa.Column('checkin_fecha', sa.String(length=10), nullable=True),
    sa.Column('checkin_hora', sa.String(length=5), nullable=True),
    sa.Column('checkin_km', sa.Integer(), nullable=True),
    sa.Column('checkin_combustible', sa.Integer(), nullable=True),
    sa.Column('checkin_descripcion', sa.Text(), nullable=True),
    sa.Column('horas_excedente', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('cargo_excedente', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('excedente_bonificado', sa.Boolean(), nullable=False),
    sa.Column('bonificado_por', sa.Integer(), nullable=True),
    sa.Column('contrato_firmado', sa.Boolean(), nullable=False),
    sa.Column('contrato_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['bonificado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alquileres_id'), 'alquileres', ['id'], unique=False)
    op.create_index(op.f('ix_alquileres_reserva_id'), 'alquileres', ['reserva_id'], unique=True)
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alquiler_id', sa.Integer(), nullable=False),
    sa.Column('url_pdf', sa.String(length=512), nullable=True),
    sa.Column('firmado', sa.Boolean(), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=False),
    sa.Column('datos_prellenados', sa.JSON(), nullable=True),
    sa.Column('link_prellenado', sa.String(length=512), nullable=True),
    sa.Column('link_expiracion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alquiler_id'], ['alquileres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_alquiler_id'), 'contratos', ['alquiler_id'], unique=True)
    op.create_index(op.f('ix_contratos_id'), 'contratos', ['id'], unique=False)
    op.create_table('echeqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('emitido', 'recibido', name='tipo_echeq'), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_emision', sa.String(length=10), nullable=False),
    sa.Column('fecha_cobro', sa.String(length=10), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'cobrado', 'rechazado', 'vencido', name='estado_echeq'), nullable=False),
    sa.Column('contraparte', sa.String(length=255), nullable=False),
    sa.Column('banco', sa.String(length=100), nullable=False),
    sa.Column('numero_cheque', sa.String(length=50), nullable=False),
    sa.Column('alquiler_id', sa.Integer(), nullable=True),
    sa.Column('gasto_id', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alquiler_id'], ['alquileres.id'], ),
    sa.ForeignKeyConstraint(['gasto_id'], ['gastos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_echeqs_fecha_cobro'), 'echeqs', ['fecha_cobro'], unique=False)
    op.create_index(op.f('ix_echeqs_id'), 'echeqs', ['id'], unique=False)
    op.create_table('movimientos_cuenta_corriente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_corriente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('debito', 'credito', name='tipo_movimiento'), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha', sa.String(length=10), nullable=False),
    sa.Column('alquiler_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alquiler_id'], ['alquileres.id'], ),
    sa.ForeignKeyConstraint(['cuenta_corriente_id'], ['cuentas_corrientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_cuenta_corriente_cuenta_corriente_id'), 'movimientos_cuenta_corriente', ['cuenta_corriente_id'], unique=False)
    op.create_index(op.f('ix_movimientos_cuenta_corriente_id'), 'movimientos_cuenta_corriente', ['id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alquiler_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('medio_pago', sa.Enum('efectivo', 'transferencia', 'tarjeta', 'cheque', 'echeq', name='medio_pago'), nullable=False),
    sa.Column('con_factura', sa.Boolean(), nullable=False),
    sa.Column('cobrado_por', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=10), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alquiler_id'], ['alquileres.id'], ),
    sa.ForeignKeyConstraint(['cobrado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_alquiler_id'), 'pagos', ['alquiler_id'], unique=False)
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_alquiler_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_movimientos_cuenta_corriente_id'), table_name='movimientos_cuenta_corriente')
    op.drop_index(op.f('ix_movimientos_cuenta_corriente_cuenta_corriente_id'), table_name='movimientos_cuenta_corriente')
    op.drop_table('movimientos_cuenta_corriente')
    op.drop_index(op.f('ix_echeqs_id'), table_name='echeqs')
    op.drop_index(op.f('ix_echeqs_fecha_cobro'), table_name='echeqs')
    op.drop_table('echeqs')
    op.drop_index(op.f('ix_contratos_id'), table_name='contratos')
    op.drop_index(op.f('ix_contratos_alquiler_id'), table_name='contratos')
    op.drop_table('contratos')
    op.drop_index(op.f('ix_alquileres_reserva_id'), table_name='alquileres')
    op.drop_index(op.f('ix_alquileres_id'), table_name='alquileres')
    op.drop_table('alquileres')
    op.drop_index(op.f('ix_tarifas_vehiculo_id'), table_name='tarifas')
    op.drop_index(op.f('ix_tarifas_id'), table_name='tarifas')
    op.drop_table('tarifas')
    op.drop_index(op.f('ix_reservas_vehiculo_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_cliente_id'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_presupuestos_id'), table_name='presupuestos')
    op.drop_table('presupuestos')
    op.drop_index(op.f('ix_gastos_vehiculo_id'), table_name='gastos')
    op.drop_index(op.f('ix_gastos_id'), table_name='gastos')
    op.drop_index(op.f('ix_gastos_fecha'), table_name='gastos')
    op.drop_table('gastos')
    op.drop_index(op.f('ix_documentos_vigencia_hasta'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_vehiculo_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_cuentas_corrientes_id'), table_name='cuentas_corrientes')
    op.drop_index(op.f('ix_cuentas_corrientes_cliente_id'), table_name='cuentas_corrientes')
    op.drop_table('cuentas_corrientes')
    op.drop_index(op.f('ix_conductores_adicionales_id'), table_name='conductores_adicionales')
    op.drop_index(op.f('ix_conductores_adicionales_cliente_id'), table_name='conductores_adicionales')
    op.drop_table('conductores_adicionales')
    op.drop_index(op.f('ix_vehiculos_patente'), table_name='vehiculos')
    op.drop_index(op.f('ix_vehiculos_id'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_auth_sub'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_clientes_nombre_completo'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_dni_cuit'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
